# Content-related messages

content.content_missing=Nodens indhold mangler: \n   node: {0} \n   l\u00e6ser: {1}  \n   V\u00e6r venlig at kontakte din systemadministrator.
content.runtime_exec.property_moved=Egenskaben ''errorCodes' er flyttet ned p\u00e5 RuntimeExec klassen

index.recovery.out_of_date=Indeksene er ikke synkroniseret med databasen.
index.tracking.starting=Genskabelse af indeks startet.
index.tracking.complete=Genskabelse af indeks fuldf\u00f8rt.
index.tracking.progress=	Processering af transaktioner omkring {0}.
index.recovery.starting=Genskabelse af indeks startet.
index.recovery.complete=Genskabelse af indeks fuldf\u00f8rt.
index.recovery.progress=	{0} % f\u00e6rdig.
index.recovery.terminated=Genskabelse af Indeks stoppet.

node.archive.msg.busy=En masse sletning eller genskabelse er under afvikling

content.http_reader.err.no_connection=Kunne ikke forbinde til Alfresco serveren via HTTP: {0}
content.http_reader.err.no_authentication=HTTP l\u00e6seren kunne ikke autentificere med serveren: {0}  \n
content.http_reader.err.check_cluster=V\u00e6r venlig at sikre at 'replicateUpdates' og 'replicateUpdatesViaCopy' er aktiveret for cachen 'org.alfresco.cache.ticketsCache'.  Check at den genrelle klynge konfiguration er korrekt og virker.
content.http_reader.err.unrecognized=En ukendt fejl opstod ved fors\u00f8g p\u00e5 hente indhold fra server:\n   Server: {0} \n   Indhold: {1} \n   HTTP Svar: {2}

metadata.extraction.err.type_conversion=Metadata udtr\u00e6k fejlede fordi en udtrukket v\u00e6rdi fejlede i konverteringen til p\u00e5kr\u00e6vet type: \n   Udtr\u00e6kker: {0} \n   M\u00e5l Egenskabets QName: {1} \n   Kr\u00e6vet Type: {2} \n   Udtrukket v\u00e6rdi: {3}

transform.err.format_or_password=Konvertering af indhold fejlede, sikkert grundet fejlformat eller adgangskode beskyttet fil.

content.routing.err.invalid_default_store=''defaultStoreName'', ''{0}'' referere ikke til et lager i ''storesByName'' ({1}).